### PR TITLE
Added ruby crab and made c crab more cursed

### PR DESCRIPTION
**Pull request by LizAinslie**
Yes that is valid c.

### CODE REVIEW

**Comment by ghost** [comment]
The C code doesnt follow the general structure of this repo, however the Ruby one is fine. I'd suggesting removing the C one.

**Comment by LizAinslie** [comment]
oof, alright. got the idea from and old repo known as "e"

**Comment by ghost** [comment]
That's fair, we just want to keep a rather consistent structure, sorry.

**Comment by ghost** [comment]
Thank you

**Comment by LizAinslie** [comment]
i'll be adding more langs soon

**Comment by ghost** [comment]
Probably best for a separate PR

**Comment by LizAinslie** [comment]
clearly

**Pull request merged**
